/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/amministratore-controller-api';
export * from './apis/contratto-controller-api';
export * from './apis/dipendente-controller-api';
export * from './apis/evento-controller-api';
export * from './apis/medica-day-controller-api';
export * from './apis/medico-controller-api';
export * from './apis/sede-controller-api';
export * from './apis/visita-medica-controller-api';

