/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Sede } from './sede';
/**
 * 
 * @export
 * @interface DipendenteDTO
 */
export interface DipendenteDTO {
    /**
     * 
     * @type {number}
     * @memberof DipendenteDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    nome?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    cognome?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    dataNascita?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    ultimaVisita?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    titoloStudi?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    codiceFiscale?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    numeroTelefono?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    sesso?: DipendenteDTOSessoEnum;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    dataPrimoContratto?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    dataAssunzioneDipendente?: string;
    /**
     * 
     * @type {string}
     * @memberof DipendenteDTO
     */
    scadenzaVisita?: string;
    /**
     * 
     * @type {Sede}
     * @memberof DipendenteDTO
     */
    sede?: Sede;
}

/**
    * @export
    * @enum {string}
    */
export enum DipendenteDTOSessoEnum {
    UOMO = 'UOMO',
    DONNA = 'DONNA',
    ALTRO = 'ALTRO'
}

