/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Distacco } from './distacco';
import { Mansione } from './mansione';
import { Sede } from './sede';
/**
 * 
 * @export
 * @interface Dipendente
 */
export interface Dipendente {
    /**
     * 
     * @type {number}
     * @memberof Dipendente
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    nome: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    cognome: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    dataNascita: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    codiceFiscale: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    sesso: DipendenteSessoEnum;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    dataPrimoContratto: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    dataAssunzioneDipendente: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    scadenzaVisita?: string;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    ultimaVisita?: string;
    /**
     * 
     * @type {Distacco}
     * @memberof Dipendente
     */
    distacco?: Distacco;
    /**
     * 
     * @type {Sede}
     * @memberof Dipendente
     */
    sede?: Sede;
    /**
     * 
     * @type {Mansione}
     * @memberof Dipendente
     */
    mansione?: Mansione;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    statoAssunzione: DipendenteStatoAssunzioneEnum;
    /**
     * 
     * @type {string}
     * @memberof Dipendente
     */
    contratto: DipendenteContrattoEnum;
    /**
     * 
     * @type {number}
     * @memberof Dipendente
     */
    intervalloScadenza?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum DipendenteSessoEnum {
    UOMO = 'UOMO',
    DONNA = 'DONNA',
    ALTRO = 'ALTRO'
}
/**
    * @export
    * @enum {string}
    */
export enum DipendenteStatoAssunzioneEnum {
    FERIE = 'FERIE',
    ATTIVO = 'ATTIVO',
    DIMESSO = 'DIMESSO',
    CONGEDOPARENTALE = 'CONGEDO_PARENTALE'
}
/**
    * @export
    * @enum {string}
    */
export enum DipendenteContrattoEnum {
    INDETERMINATO = 'INDETERMINATO',
    DETERMINATO = 'DETERMINATO',
    APPRENDISTATO = 'APPRENDISTATO',
    STAGE = 'STAGE'
}

