/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DocumentDTO
 */
export interface DocumentDTO {
    /**
     * 
     * @type {Date}
     * @memberof DocumentDTO
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof DocumentDTO
     */
    lastModifiedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentDTO
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentDTO
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentDTO
     */
    originalFilename?: string;
}
