/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventoCriteria
 */
export interface EventoCriteria {
    /**
     * 
     * @type {number}
     * @memberof EventoCriteria
     */
    idDipendente?: number;
    /**
     * 
     * @type {string}
     * @memberof EventoCriteria
     */
    nome?: string;
    /**
     * 
     * @type {string}
     * @memberof EventoCriteria
     */
    cognome?: string;
    /**
     * 
     * @type {string}
     * @memberof EventoCriteria
     */
    codiceFiscale?: string;
    /**
     * 
     * @type {string}
     * @memberof EventoCriteria
     */
    nomeEvento?: EventoCriteriaNomeEventoEnum;
    /**
     * 
     * @type {Date}
     * @memberof EventoCriteria
     */
    timestamp?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventoCriteria
     */
    dataDal?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventoCriteria
     */
    dataAl?: Date;
}

/**
    * @export
    * @enum {string}
    */
export enum EventoCriteriaNomeEventoEnum {
    VISITAMEDICAEFFETTUATA = 'VISITA_MEDICA_EFFETTUATA',
    VISITAMEDICAANNULLATA = 'VISITA_MEDICA_ANNULLATA',
    VISITAMEDICACONCLUSA = 'VISITA_MEDICA_CONCLUSA',
    VISITAMEDICANONEFFETTUATA = 'VISITA_MEDICA_NON_EFFETTUATA',
    VISITAMEDICASCADUTA = 'VISITA_MEDICA_SCADUTA',
    VISITAMEDICAPRENOTATA = 'VISITA_MEDICA_PRENOTATA',
    SCADENZAVISITAMODIFICATA = 'SCADENZA_VISITA_MODIFICATA',
    ELIMINATOCERTIFICATOMEDICO = 'ELIMINATO_CERTIFICATO_MEDICO',
    ALLEGATOCERTIFICATOMEDICO = 'ALLEGATO_CERTIFICATO_MEDICO',
    ASSEGNATOILMEDICALDAY = 'ASSEGNATO_IL_MEDICALDAY'
}

