/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dipendente } from './dipendente';
import { MedicalDay } from './medical-day';
/**
 * 
 * @export
 * @interface EventoDTO
 */
export interface EventoDTO {
    /**
     * 
     * @type {number}
     * @memberof EventoDTO
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof EventoDTO
     */
    timestamp?: Date;
    /**
     * 
     * @type {Dipendente}
     * @memberof EventoDTO
     */
    dipendente?: Dipendente;
    /**
     * 
     * @type {MedicalDay}
     * @memberof EventoDTO
     */
    medicalDay?: MedicalDay;
    /**
     * 
     * @type {string}
     * @memberof EventoDTO
     */
    tipologiaEvento?: EventoDTOTipologiaEventoEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum EventoDTOTipologiaEventoEnum {
    VISITAMEDICAEFFETTUATA = 'VISITA_MEDICA_EFFETTUATA',
    VISITAMEDICAANNULLATA = 'VISITA_MEDICA_ANNULLATA',
    VISITAMEDICACONCLUSA = 'VISITA_MEDICA_CONCLUSA',
    VISITAMEDICANONEFFETTUATA = 'VISITA_MEDICA_NON_EFFETTUATA',
    VISITAMEDICASCADUTA = 'VISITA_MEDICA_SCADUTA',
    VISITAMEDICAPRENOTATA = 'VISITA_MEDICA_PRENOTATA',
    SCADENZAVISITAMODIFICATA = 'SCADENZA_VISITA_MODIFICATA',
    ELIMINATOCERTIFICATOMEDICO = 'ELIMINATO_CERTIFICATO_MEDICO',
    ALLEGATOCERTIFICATOMEDICO = 'ALLEGATO_CERTIFICATO_MEDICO',
    ASSEGNATOILMEDICALDAY = 'ASSEGNATO_IL_MEDICALDAY'
}

