/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LongFilter } from './long-filter';
import { StringFilter } from './string-filter';
/**
 * 
 * @export
 * @interface MedicoCriteria
 */
export interface MedicoCriteria {
    /**
     * 
     * @type {StringFilter}
     * @memberof MedicoCriteria
     */
    nome?: StringFilter;
    /**
     * 
     * @type {StringFilter}
     * @memberof MedicoCriteria
     */
    cognome?: StringFilter;
    /**
     * 
     * @type {LongFilter}
     * @memberof MedicoCriteria
     */
    sedeId?: LongFilter;
}
