/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LongFilter } from './long-filter';
import { RangeFilterLocalDate } from './range-filter-local-date';
import { StatoMedicalDayFilter } from './stato-medical-day-filter';
/**
 * 
 * @export
 * @interface MedicalDayCriteria
 */
export interface MedicalDayCriteria {
    /**
     * 
     * @type {LongFilter}
     * @memberof MedicalDayCriteria
     */
    idMedico?: LongFilter;
    /**
     * 
     * @type {LongFilter}
     * @memberof MedicalDayCriteria
     */
    idSede?: LongFilter;
    /**
     * 
     * @type {RangeFilterLocalDate}
     * @memberof MedicalDayCriteria
     */
    dataGiorno?: RangeFilterLocalDate;
    /**
     * 
     * @type {StatoMedicalDayFilter}
     * @memberof MedicalDayCriteria
     */
    medicalDayStato?: StatoMedicalDayFilter;
}
