/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RangeFilterLocalDate } from './range-filter-local-date';
/**
 * 
 * @export
 * @interface RangeFilterLocalDate
 */
export interface RangeFilterLocalDate {
    /**
     * 
     * @type {string}
     * @memberof RangeFilterLocalDate
     */
    equals?: string;
    /**
     * 
     * @type {string}
     * @memberof RangeFilterLocalDate
     */
    notEquals?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RangeFilterLocalDate
     */
    specified?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RangeFilterLocalDate
     */
    _in?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RangeFilterLocalDate
     */
    notIn?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RangeFilterLocalDate
     */
    greaterThan?: string;
    /**
     * 
     * @type {string}
     * @memberof RangeFilterLocalDate
     */
    lessThan?: string;
    /**
     * 
     * @type {string}
     * @memberof RangeFilterLocalDate
     */
    greaterThanOrEqual?: string;
    /**
     * 
     * @type {string}
     * @memberof RangeFilterLocalDate
     */
    lessThanOrEqual?: string;
    /**
     * 
     * @type {RangeFilterLocalDate}
     * @memberof RangeFilterLocalDate
     */
    lessOrEqualThan?: RangeFilterLocalDate;
    /**
     * 
     * @type {RangeFilterLocalDate}
     * @memberof RangeFilterLocalDate
     */
    greaterOrEqualThan?: RangeFilterLocalDate;
}
