/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SedeDTO
 */
export interface SedeDTO {
    /**
     * 
     * @type {number}
     * @memberof SedeDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SedeDTO
     */
    denominazione?: string;
    /**
     * 
     * @type {string}
     * @memberof SedeDTO
     */
    via?: string;
    /**
     * 
     * @type {string}
     * @memberof SedeDTO
     */
    citta?: string;
    /**
     * 
     * @type {string}
     * @memberof SedeDTO
     */
    civico?: string;
    /**
     * 
     * @type {string}
     * @memberof SedeDTO
     */
    cap?: string;
    /**
     * 
     * @type {string}
     * @memberof SedeDTO
     */
    provincia?: string;
}
