/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StatoMedicalDayFilter
 */
export interface StatoMedicalDayFilter {
    /**
     * 
     * @type {string}
     * @memberof StatoMedicalDayFilter
     */
    equals?: StatoMedicalDayFilterEqualsEnum;
    /**
     * 
     * @type {string}
     * @memberof StatoMedicalDayFilter
     */
    notEquals?: StatoMedicalDayFilterNotEqualsEnum;
    /**
     * 
     * @type {boolean}
     * @memberof StatoMedicalDayFilter
     */
    specified?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatoMedicalDayFilter
     */
    _in?: Array<StatoMedicalDayFilterInEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatoMedicalDayFilter
     */
    notIn?: Array<StatoMedicalDayFilterNotInEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum StatoMedicalDayFilterEqualsEnum {
    INLAVORAZIONE = 'IN_LAVORAZIONE',
    COMPLETO = 'COMPLETO'
}
/**
    * @export
    * @enum {string}
    */
export enum StatoMedicalDayFilterNotEqualsEnum {
    INLAVORAZIONE = 'IN_LAVORAZIONE',
    COMPLETO = 'COMPLETO'
}
/**
    * @export
    * @enum {string}
    */
export enum StatoMedicalDayFilterInEnum {
    INLAVORAZIONE = 'IN_LAVORAZIONE',
    COMPLETO = 'COMPLETO'
}
/**
    * @export
    * @enum {string}
    */
export enum StatoMedicalDayFilterNotInEnum {
    INLAVORAZIONE = 'IN_LAVORAZIONE',
    COMPLETO = 'COMPLETO'
}

