/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StringFilter
 */
export interface StringFilter {
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    equals?: string;
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    notEquals?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StringFilter
     */
    specified?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof StringFilter
     */
    _in?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StringFilter
     */
    notIn?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    contains?: string;
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    doesNotContain?: string;
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    starts?: string;
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    ends?: string;
}
