/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateMedicoDTO
 */
export interface UpdateMedicoDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    nome: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    cognome: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    dataNascita: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    titoloStudi?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    codiceFiscale: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    numeroTelefono?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicoDTO
     */
    sesso: UpdateMedicoDTOSessoEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMedicoDTO
     */
    societa?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateMedicoDTOSessoEnum {
    UOMO = 'UOMO',
    DONNA = 'DONNA',
    ALTRO = 'ALTRO'
}

