/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Distacco } from './distacco';
import { Mansione } from './mansione';
import { Sede } from './sede';
/**
 * 
 * @export
 * @interface UpdateDipendenteDTO
 */
export interface UpdateDipendenteDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    nome?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    cognome?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    dataNascita: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    titoloStudi?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    codiceFiscale?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    numeroTelefono?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    sesso?: UpdateDipendenteDTOSessoEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    dataPrimoContratto?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    dataAssunzioneDipendente?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    ultimaVisita?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    statoAssunzione?: UpdateDipendenteDTOStatoAssunzioneEnum;
    /**
     * 
     * @type {Distacco}
     * @memberof UpdateDipendenteDTO
     */
    distacco?: Distacco;
    /**
     * 
     * @type {Sede}
     * @memberof UpdateDipendenteDTO
     */
    sede?: Sede;
    /**
     * 
     * @type {Mansione}
     * @memberof UpdateDipendenteDTO
     */
    mansione?: Mansione;
    /**
     * 
     * @type {string}
     * @memberof UpdateDipendenteDTO
     */
    contratto?: UpdateDipendenteDTOContrattoEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateDipendenteDTOSessoEnum {
    UOMO = 'UOMO',
    DONNA = 'DONNA',
    ALTRO = 'ALTRO'
}
/**
    * @export
    * @enum {string}
    */
export enum UpdateDipendenteDTOStatoAssunzioneEnum {
    FERIE = 'FERIE',
    ATTIVO = 'ATTIVO',
    DIMESSO = 'DIMESSO',
    CONGEDOPARENTALE = 'CONGEDO_PARENTALE'
}
/**
    * @export
    * @enum {string}
    */
export enum UpdateDipendenteDTOContrattoEnum {
    INDETERMINATO = 'INDETERMINATO',
    DETERMINATO = 'DETERMINATO',
    APPRENDISTATO = 'APPRENDISTATO',
    STAGE = 'STAGE'
}

