/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dipendente } from './dipendente';
import { LocalTime } from './local-time';
import { MedicalDay } from './medical-day';
/**
 * 
 * @export
 * @interface VisitaMedicaDTO
 */
export interface VisitaMedicaDTO {
    /**
     * 
     * @type {number}
     * @memberof VisitaMedicaDTO
     */
    id?: number;
    /**
     * 
     * @type {LocalTime}
     * @memberof VisitaMedicaDTO
     */
    oraVisita?: LocalTime;
    /**
     * 
     * @type {MedicalDay}
     * @memberof VisitaMedicaDTO
     */
    medicalDay?: MedicalDay;
    /**
     * 
     * @type {Dipendente}
     * @memberof VisitaMedicaDTO
     */
    dipendente?: Dipendente;
    /**
     * 
     * @type {boolean}
     * @memberof VisitaMedicaDTO
     */
    certificato?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaDTO
     */
    statoVisitaMedica?: VisitaMedicaDTOStatoVisitaMedicaEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum VisitaMedicaDTOStatoVisitaMedicaEnum {
    INSERITA = 'INSERITA',
    EFFETTUATA = 'EFFETTUATA',
    NONEFFETTUATA = 'NON_EFFETTUATA'
}

