/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StringFilter } from './string-filter';
/**
 * 
 * @export
 * @interface VisitaMedicaCriteria
 */
export interface VisitaMedicaCriteria {
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaCriteria
     */
    dataMedicalDayInizio?: string;
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaCriteria
     */
    dataMedicalDayFine?: string;
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaCriteria
     */
    statoVisitaMedica?: VisitaMedicaCriteriaStatoVisitaMedicaEnum;
    /**
     * 
     * @type {StringFilter}
     * @memberof VisitaMedicaCriteria
     */
    idCertificato?: StringFilter;
}

/**
    * @export
    * @enum {string}
    */
export enum VisitaMedicaCriteriaStatoVisitaMedicaEnum {
    INSERITA = 'INSERITA',
    EFFETTUATA = 'EFFETTUATA',
    NONEFFETTUATA = 'NON_EFFETTUATA'
}

