/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentDTO } from './document-dto';
/**
 * 
 * @export
 * @interface VisitaMedicaCertificatoDTO
 */
export interface VisitaMedicaCertificatoDTO {
    /**
     * 
     * @type {DocumentDTO}
     * @memberof VisitaMedicaCertificatoDTO
     */
    documentDTO?: DocumentDTO;
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaCertificatoDTO
     */
    idCertificato?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VisitaMedicaCertificatoDTO
     */
    idoneo?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaCertificatoDTO
     */
    rinnovoScadenzaIdoneita?: string;
    /**
     * 
     * @type {string}
     * @memberof VisitaMedicaCertificatoDTO
     */
    prescrizione?: string;
}
